name: Garnet Mirror Repository
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        run: |
          pip install mercurial
          git clone https://github.com/frej/fast-export
          hg clone https://hg.sr.ht/~icefox/garnet garnet-mercurial
          mkdir git-repo
          cd git-repo
          git init
          git config core.ignoreCase false
          cd ../garnet-mercurial
          hg log --template "{author}={author}\n" | sort | uniq > committers.txt
          cd ../garnet-git
          ../fast-export/hg-fast-export.sh -r ../garnet-mercurial -A ../garnet-mercurial/committers.txt -M main
          git checkout
          git remote set-url --push origin "https://qexat:${{ secrets.SOURCE_TOKEN_GARNET }}@github.com/qexat/garnet.git"
          git push --mirror
